### ISSUE TITLE
Support for Post field

### ISSUE THREAD

**Issue by stevygee** [wpmetabox/mb-elementor-integrator#1]
Thanks for this extension, I already like it a lot!

I would like to display the value of a post field (one or multiple posts) as a link. Ideally selecting both the post title and permalink should be possible, so a link to the selected post can be displayed.

**Comment by rilwis** [comment]
Hi @stevygee ,

Sorry for the delay. You can use a Heading or Text module and connect with the post field. The plugin will output the post title with link into the module.
