### ISSUE TITLE
Error with rwmb_get_registry()

### ISSUE THREAD

**Issue by danielswiatek** [wpmetabox/mb-elementor-integrator#2]
If i install and try to use the plugin with Elementor i get the following Error: 
```Fatal error: Uncaught Error: Call to undefined function MBEI\Traits\rwmb_get_registry() in /Users/daniel/src/wordpress-codeanker/wp-content/plugins/mb-elementor-integrator/src/Traits/Base.php:32 Stack trace: #0 /Users/daniel/src/wordpress-codeanker/wp-content/plugins/mb-elementor-integrator/src/Traits/Post.php(12): MBEI\Tags\Post\Text->get_fields_by_object_type('post') #1 /Users/daniel/src/wordpress-codeanker/wp-content/plugins/mb-elementor-integrator/src/Traits/Base.php(27): MBEI\Tags\Post\Text->get_option_groups() #2 /Users/daniel/src/wordpress-codeanker/wp-content/plugins/elementor/core/dynamic-tags/base-tag.php(173): MBEI\Tags\Post\Text->_register_controls() #3 /Users/daniel/src/wordpress-codeanker/wp-content/plugins/elementor/includes/base/controls-stack.php(488): Elementor\Core\DynamicTags\Base_Tag->init_controls() #4 /Users/daniel/src/wordpress-codeanker/wp-content/plugins/elementor/includes/base/controls-stack.php(281): Elementor\Controls_Stack->get_stack() #5 /Users/daniel/src/wordpress-codeanker/wp-content/plugi in /Users/daniel/src/wordpress-codeanker/wp-content/plugins/mb-elementor-integrator/src/Traits/Base.php on line 32```

**Comment by rilwis** [comment]
Have you installed the Meta Box plugin first?
