### ISSUE TITLE
Bug: container with background image not working

### ISSUE THREAD

**Issue by huubl** [wpmetabox/mb-elementor-integrator#25]
Hi,

I'm using a container with a background image filled with the image advanced field. The last update broke this.

A container is `NULL` here:
https://github.com/wpmetabox/mb-elementor-integrator/blob/374cd46e8f4a5940ad5b05f4346a9b968c0ec412/src/Traits/Fields/Image.php#L22

The default function doesn't work for the background image:

https://github.com/wpmetabox/mb-elementor-integrator/blob/374cd46e8f4a5940ad5b05f4346a9b968c0ec412/src/Traits/Fields/Image.php#L54-L56

This fixes my problem:
https://github.com/wpmetabox/mb-elementor-integrator/pull/24

**Comment by rilwis** [comment]
Thanks for your feedback. Looks like your fix will apply the "single" method to all widgets that can't get name. And that will disable the "default" method.

I'll dig more into the problem and will try to find a better solution. Currently, with your suggestion, I'm thinking about listing all widgets that have "multiple" images like carousel or gallery, and set the default to "single" image.

By the way, are you using `image_advanced` field? Can you try switching it to `single_image`?

**Comment by rilwis** [comment]
PR merged!
