### ISSUE TITLE
Add Support for Number

### ISSUE THREAD

**Issue by dmccan** [wpmetabox/mb-elementor-integrator#4]
The Elementor widget Star Rating looks for a number for the rating

```php
		$this->add_control(
			'rating',
			[
				'label' => __( 'Rating', 'elementor' ),
				'type' => Controls_Manager::NUMBER,
				'min' => 0,
				'max' => 10,
				'step' => 0.1,
				'default' => 5,
				'dynamic' => [
					'active' => true,
				],
			]
		);
```
When you click the dynamic icon for the rating the Meta Box select option does not show. 

![mb-elementor-star-rating](https://user-images.githubusercontent.com/2622805/76242342-95bffd00-6204-11ea-93e3-e0bafd5c7d62.png)

Here is the definition of the number field in MB Custom FIelds

![mb-number-field](https://user-images.githubusercontent.com/2622805/76242881-652c9300-6205-11ea-8bfb-608e195e8e1b.png)

**Comment by rilwis** [comment]
Hi @dmccan ,

Thanks for your feedback. I'll add support for it.
