### ISSUE TITLE
Question about group field and elementor integration

### ISSUE THREAD

**Issue by smatzis** [wpmetabox/mb-elementor-integrator#5]
Hello, how are you? Just a couple of questions because ...
First of all, is it possible to create an elementor template for a group field?
An if yes, is it possible to use this template inside another Elementor template like a post loop or archive template etc?
I know this is possible with Jetengine repeaters and ACF repeaters combined with various elementor plugins but i cannot find any info about meta box...

Thank you in advance!
Regards

**Comment by rilwis** [comment]
Hi,

Yes, you can create a template for groups via [MB Views](https://metabox.io/plugins/mb-views/). It allows you to build the view template with HTML (Twig)/CSS/JS. Then you can insert the view into your Elementor element via shortcode.

If you're looking for a direct way to build the template for groups (repeatable) with built-in Elementor element, like you see with Jetengine and ACF, then it's not possible at the moment.

Thanks,
Anh
